spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_zBcfQyeTy
          jwk-set-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_zBcfQyeTy/.well-known/jwks.json

